Fix: Make jest code transformation work again
Current babel transform target rules look broken. Running test yields
these error messages:

```txt
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { shallow } from '@vue/test-utils';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
```

Webpack builds chunks for browsers and jest runs tests in nodejs
exclusively. So changing the default babel config to target browsers
seems to fix the issue.